### ISSUE TITLE
StarRatinngOptions glowColor is being ignored

### ISSUE THREAD

**Issue by kristijorgji** [Skyost/RateMyApp#101]
```
starRatingOptions: StarRatingOptions(
      initialRating: 0.0,
      glowColor: Colors.green,
    ),
```

Still the stars are shown in orange

I migrated code from rate_my_app: ^0.6.1+3 to rate_my_app: ^1.1.0+1

Previously this worked fine with old format of styles which I found better

```
starRatingOptions: StarRatingOptions(
        initialRating: null,
        starsBorderColor: Colors.green,
        starsFillColor: Colors.green),
```

with new version I converted to

```
    starRatingOptions: StarRatingOptions(
      initialRating: 0.0,
      glowColor: Colors.green,
    ),
```
but as mentioned color does not work. Would be great to again have possiblilty change border and star fill color like in previous version, was very clear customisable and worked great

**Comment by Sadeesha-Sath** [comment]
Glow color does not modify widget color. It only changes the 'glow' when you interact with the rating bar.

I added a PR to fix this issue and give the ability to use custom widgets. Hopefully, it will get merged. Or maybe somebody will come up with a better solution.

**Comment by kristijorgji** [comment]
Hi, thanks I would suggest you just revert it as it was back in old version  ^0.6.1+3, worked fantastic allowing to customise both colors like:

```
starRatingOptions: StarRatingOptions(
        initialRating: null,
        starsBorderColor: Colors.green,
        starsFillColor: Colors.green),
```

**Comment by Sadeesha-Sath** [comment]
Well, I added only the item color change. I'm not a writer of this repo, so I don't know why they changed it, but I think that it is because of the underline dependency, 'flutter_rating_bar' changed. It has no longer has those fill-color and border-color properties. So I don't know whether it is possible to revert those changes. But I'll try to come up with some workaround to give support for both color changes.

**Comment by Sadeesha-Sath** [comment]
This PR #104 now adds support for border color customization as well
