### ISSUE TITLE
Custom star rating on ios not working...

### ISSUE THREAD

**Issue by gutisalex** [Skyost/RateMyApp#107]
**Describe the bug**
Shows star rate dialog custom text only on android and not on ios

**To Reproduce**
1. Add a star rate dialog
2. Set custom title 'Do you like the app?'
3. Set custom message 'Would you like to rate our app?'
4. Set initial rating to 3
5. Set minDays and minLaunches to 0

**Code example**
```dart
rateMyApp.showStarRateDialog(
              context,
              title: 'Do you like the app?',
              message:
                  'Would you like to rate our app?',
              starRatingOptions: StarRatingOptions(initialRating: 3),
              actionsBuilder: actionsBuilder,
              onDismissed: () =>
                  rateMyApp.callEvent(RateMyAppEventType.laterButtonPressed),
            );
```

**Expected behavior**
A 5 star rating should pop up after start and showing the custom title, the text and 3 stars preselected.

**Screenshots**

![rating](https://user-images.githubusercontent.com/52527652/126320597-db76d023-6da2-483c-89d8-67eaffd3be42.jpg)

Edit: Or is iOS just not meant to be customized?! Then I have not fully understand the plugin yet...

**Comment by Skyost** [comment]
> Or is iOS just not meant to be customized?! Then I have not fully understand the plugin yet...

Depends what value you pass to `ignoreNativeDialog` :wink:
