### ISSUE TITLE
Get result from launchNativeReviewDialog (Success/No Success)

### ISSUE THREAD

**Issue by Termtime** [Skyost/RateMyApp#110]
**Is your feature request related to a problem? Please describe.**
I would like to track with my analytics whenever a user rated the app using the NativeReviewDialog (for both iOS and Android) but so far it seems like it's not possible. I ideally want to be able to track how many stars I got from the review dialog, or in the case that is not possible, at least whether or not the app was rated or the dialog was dismissed.

**Describe the solution you'd like**
Return a response with either the number of stars given in the NativeReviewDialog or if the dialog was dismissed

**Describe alternatives you've considered**
So far no alternatives have been considered

**Comment by Skyost** [comment]
> I would like to track with my analytics whenever a user rated the app using the NativeReviewDialog (for both iOS and Android)

It's not possible. Google and Apple doesn't provide any callback in their dialogs.
