### ISSUE TITLE
TextDirection.rtl. apply right direction fot message text.

### ISSUE THREAD

**Issue by dryasbk** [Skyost/RateMyApp#114]
When trying to write in  Arabic text, even with textAlignment.right the ! or . will be in a wrong position.

**Describe the solution you'd like**
Adding the TextDirection option

**Describe alternatives you've considered**
add TextDirection either TextDirection.rtl or TextDirection.lft

**Additional context**
also if possible add a Button style option

**Comment by dryasbk** [comment]
Just to edit dialog.dart file at line 78 :
child: Padding(
        padding: dialogStyle.messagePadding,
        child: Text(
          message,
          textDirection: TextDirection.rtl,   # this line to message text
          style: dialogStyle.messageStyle,
          textAlign: dialogStyle.messageAlign,
        ),
      ),

**Comment by Skyost** [comment]
Just use a custom `contentBuilder` :wink:
