### ISSUE TITLE
On New Version of Flutter

### ISSUE THREAD

**Issue by alixumer** [Skyost/RateMyApp#122]
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-1.1.2/lib/src/widgets.dart:49:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) {

**Comment by Skyost** [comment]
Fixed in #121.
