### ISSUE TITLE
Bug minimumDate

### ISSUE THREAD

**Issue by theahmadjawad** [Skyost/RateMyApp#124]
Unhandled Exception: LateInitializationError: Field 'minimumDate' has not been initialized.

I am getting this error when checking shouldOpenDialog.

**Comment by srihari9n** [comment]
@theahmadjawad  make sure you call .init(); before checking for shouldOpenDialog.

**Comment by Skyost** [comment]
Exactly @srihari9n !

**Comment by frevostudios** [comment]
I have the same error, even call init()

`    _rateMyApp.init().then((_) {
      if(_rateMyApp.shouldOpenDialog) {
        _rateMyApp.showRateDialog(
        ...
        `

**Comment by Skyost** [comment]
Are you sure your app doesn't make any call to Rate my app before that `init()` call ?

**Comment by frevostudios** [comment]
I didn't reproduce this bug again. Maybe I was testing with a wrong version, maybe calling to rate before init(). So, I'm thinking that was my mistake.

I'm monitoring if this error happens again. 
This is the code that I'm using now: 

`RateMyApp _rateMyApp = RateMyApp(
    preferencesPrefix: 'rateMyApp_',
    minDays: 1,
    minLaunches: 2,
    remindDays: 3,
    remindLaunches: 3,
    googlePlayIdentifier: ConstantsConfig.playStoreId
  );
  
  
  _rateMyApp.init().then((_) {
        if(_rateMyApp.shouldOpenDialog) {
          AppLog.printLog('ReviewInAppUtils.rateApp - show');
          _rateMyApp.showRateDialog(... `

**Comment by Skyost** [comment]
Great !
