### ISSUE TITLE
Package is not working in testflight.

### ISSUE THREAD

**Issue by greatschism** [Skyost/RateMyApp#126]
It works on my iPhone/iPad and the simulator during test, but does not work in test flight. I tried building it in release mode and I get an error.

```
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace
```
I go to Xcode and it install on my iPhone, and the module work great. I am not sure what I am missing.

**Comment by Skyost** [comment]
See #1 for testflight.
