### ISSUE TITLE
Duplicate class com.google.android.play.core.appupdate.AppUpdateInfo found in modules jetified-app-update-2.0.1-runtime

### ISSUE THREAD

**Issue by danielmessi13** [Skyost/RateMyApp#129]
**Describe the bug**
There is a deprecated implementation in build.gradle that conflicts with other packages that use updated implementations. I'm not sure that's the reason, but it appears to be.

> The Play Core Java and Kotlin Library has been partitioned into multiple per-feature Android libraries. This reduces the size Play Core libraries add to your app and allows for faster release cycles of the individual features.

https://developer.android.com/guide/playcore#java-kotlin-in-app-review

**To Reproduce**
1. Add `in_app_update` package
2. Add `rate_my_app` package
3. Try run in Android

**Screenshots**
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/29608634/222475513-40de34e0-15b7-4424-a7b1-2ef7b809d8e5.png">

**Smartphone:**
 - Device: Android Pixel 4 
 - OS: Android 12
 - Version: API 31

**Additional context**
I did a test update and it worked:

change this:

```
implementation 'com.google.android.play:core:1.8.0'
```
 

to

```
implementation 'com.google.android.play:review:2.0.1'
implementation 'com.google.android.play:review-ktx:2.0.1'
```

**Comment by danielmessi13** [comment]
I created a PR solving this, in case I see that it makes sense and doesn't bring any problems to the package 

@Skyost

**Comment by lesonlhld** [comment]
Hello @Skyost,

I was wondering if it would be possible for you to release a new version on pub.dev to fix this problem. Thank you in advance for your help!

Best regards,

**Comment by Skyost** [comment]
Yes, for sure. I also have to release a new version of FlutterWeekView. I'll do it tomorrow.
