### ISSUE TITLE
Could not resolve project :rate_my_app

### ISSUE THREAD

**Issue by Noraiz322** [Skyost/RateMyApp#134]
I was using this library since long time ago and it was working fine. I updated some of firebase libraries yesterday and after some time it started giving me following error regarding rate_my_app library. I could not understand what is the connection between these libraries. while commenting this library everything works fine at my end. 
Can you help me to resolve the following issue.

* What went wrong:
Could not determine the dependencies of task ':app:compileDevelopmentDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:developmentDebugCompileClasspath'.
   > Could not resolve project :rate_my_app.
     Required by:
         project :app
      > No matching configuration of project :rate_my_app was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'app' with value 'development' but:
          - None of the consumable configurations have attributes.

**Comment by Skyost** [comment]
Which version of the plugin are you using ? If it's the latest (2.0.0), make sure you're using Android Gradle Plugin v8 at least.

**Comment by Noraiz322** [comment]
I am using following library 'rate_my_app: ^1.1.3'
buildscript {
  // ...

  dependencies {
    classpath 'com.android.tools.build:gradle:4.1.0'
    // ...
  }
}

When I added the namespace for my project as you mentioned in app/build.gradle. Error is changed now and didn't get success yet. Here is the error:

* What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_8hfcje9qzf6viw7vmnpeozlc2.android() is applicable for argument types: (build_8hfcje9qzf6viw7vmnpeozlc2$_run_closure2) values: [build_8hfcje9qzf6viw7vmnpeozlc2$_run_closure2@32e5480c]

**Comment by Skyost** [comment]
Well, if you're using 1.1.3, this doesn't apply to you. If you encountered this problem after upgrading other libraries, make sure to `flutter clean` before running.

**Comment by Noraiz322** [comment]
I got it resolved by cache clearing and removing/adding library. Thanks for prompt reply. Really appreciable.

**Comment by Skyost** [comment]
Cool then :wink:
