### ISSUE TITLE
A problem occurred evaluating project ':rate_my_app'.

### ISSUE THREAD

**Issue by rajaarav0** [Skyost/RateMyApp#136]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/shoony/.pub-cache/hosted/pub.dev/rate_my_app-2.0.0/android/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':rate_my_app'.
> No signature of method: build_ezlv1yh19f1jyx9bxv8z2nkl1.android() is applicable for argument types: (build_ezlv1yh19f1jyx9bxv8z2nkl1$_run_closure2) values: [build_ezlv1yh19f1jyx9bxv8z2nkl1$_run_closure2@3f458003]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Exception: Gradle task assembleDebug failed with exit code 1
<img width="876" alt="Screenshot 2023-06-05 at 3 11 01 PM" src="https://github.com/Skyost/RateMyApp/assets/64748053/590cd69f-f4fa-4755-b092-63b2a9216372">

**Comment by Skyost** [comment]
Try to `flutter clean` your project before building it.

**Comment by Skyost** [comment]
Are you using AGP 8 ?

**Comment by rajaarav0** [comment]
graddle-wrapper.properties is distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
and
build/gradle is  classpath 'com.android.tools.build:gradle:4.1.0'

**Comment by rajaarav0** [comment]
> Are you using AGP 8 ?

graddle-wrapper.properties is distributionUrl=https://services.gradle.org/distributions/gradle-6.7-all.zip
and
build/gradle is classpath 'com.android.tools.build:gradle:4.1.0'

**Comment by Skyost** [comment]
This the problem (see the changelog) ! Either migrate to AGP 8 or downgrade RateMyApp.
