### ISSUE TITLE
Error while executing flutter run after adding the dependency and crash

### ISSUE THREAD

**Issue by wasif2mehmood** [Skyost/RateMyApp#139]
**Describe the bug**
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class kotlin.collections.jdk8.CollectionsJDK8Kt found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)
     Duplicate class kotlin.internal.jdk8.JDK8PlatformImplementations found in modules jetified-kotlin-stdlib-1.8.0 (org.jetbrains.kotlin:kotlin-stdlib:1.8.0) and jetified-kotlin-stdlib-jdk8-1.7.10 (org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10)

**To Reproduce**
after adding the dependency of rate my app and running flutter pub get when i execute flutter run command this error occurs

**Screenshots**

![image](https://github.com/Skyost/RateMyApp/assets/101115606/010438ad-03c2-420d-ab02-6759584e7290)

it is something about kotlin version conflict i tried version overriding but did not worked.

**Comment by Skyost** [comment]
I don't think that this error is related to this plugin. Try to `flutter clean && flutter pub get`.

**Comment by kemalilketuna** [comment]
I have same error

**Comment by Skyost** [comment]
> I don't think that this error is related to this plugin. Try to `flutter clean && flutter pub get`.

**Comment by jrmarkham** [comment]
I had a similar issue (different plugin). I removed the duplicate dependency from android/app/build.gradle and boom it compiled.
