### ISSUE TITLE
shouldOpenDialog always returns false

### ISSUE THREAD

**Issue by ItsYasser** [Skyost/RateMyApp#141]
The method shouldOpenDialog is always returning false as i clearly set minDate as 0 and minLaunch as 0 but it always returns false

**Expected behavior**
to return true if the conditions are met

**Screenshots**
![image](https://github.com/Skyost/RateMyApp/assets/87891892/8b079fae-ebb8-4ced-bf7e-1f0f2c8e8bba)
here it's clearly showing false as you can see minLaunch is 7 and the currentLaunch is 8

**Additional context**
Tested on android

**Comment by Skyost** [comment]
It also depends on the minimum valid date.

**Comment by ItsYasser** [comment]
How to change that ? because i  can't find it 
this is all the object has : 
![image](https://github.com/Skyost/RateMyApp/assets/87891892/0b6e5752-8ba6-4f3b-81ec-58cca249a401)

**Comment by ItsYasser** [comment]
> It also depends on the minimum valid date.

How to change that ? because i can't find it
this is all the object has :

![image](https://github.com/Skyost/RateMyApp/assets/87891892/62d8c95b-d802-46b0-9263-1da4daf836b9)

**Comment by Skyost** [comment]
It's the `minDays` parameter (see https://github.com/Skyost/RateMyApp/blob/master/lib/src/conditions.dart#L48).

**Comment by ItsYasser** [comment]
> It's the `minDays` parameter (see https://github.com/Skyost/RateMyApp/blob/master/lib/src/conditions.dart#L48).

But its clear in my issue that i did minDays 0 and its still not working ?!

**Comment by Skyost** [comment]
Well, yes, but it also depends on whether you already clicked on, for example, _Remind me later_ while having a non null "remind days". Try to reset the plugin settings using `rateMyApp.reset()`.

**Comment by ItsYasser** [comment]
Now it works yes , Thank you🙏
