### ISSUE TITLE
Allow editing of the dialog

### ISSUE THREAD

**Issue by AnasElbattra** [Skyost/RateMyApp#143]
**Is your feature request related to a problem? Please describe.**
I need to customize the UI for the rate dialog but it is impossible 

**Describe the solution you'd like**
1- I need to change the color of each button separately 
2- I need a bool variable if it's true the action button will wrap with the `Wrap` widget with some edits in the Wrap widget like spacing and alignment 
3- add an icon in the dialog 

**Additional context**
I'm hoping to achieve this example.

![d](https://github.com/Skyost/RateMyApp/assets/75434006/7e7a01d8-f9ab-4476-9754-70836a09cacf)

**Comment by Skyost** [comment]
Use both `contentBuilder` and `actionsBuilder` arguments of `showRateDialog()` or just display your custom dialog 🙂

**Comment by AnasElbattra** [comment]
> Use both `contentBuilder` and `actionsBuilder` arguments of `showRateDialog()` or just display your custom dialog 🙂

Ok, How I can use the function for the three button when I use action builder

**Comment by Skyost** [comment]
It works like every other builder in Flutter, except that you have to return a list of widgets (`TextButton`s for instance). See the default implementation : https://github.com/Skyost/RateMyApp/blob/master/lib/src/dialogs.dart#L96.

**Comment by AnasElbattra** [comment]
> It works like every other builder in Flutter, except that you have to return a list of widgets (`TextButton`s for instance). See the default implementation : https://github.com/Skyost/RateMyApp/blob/master/lib/src/dialogs.dart#L96.

Nice, I need example to implement these  (rate-later-no) correctly when I press on the button

**Comment by AnasElbattra** [comment]
Thank you for your help
