### ISSUE TITLE
Possibility to further customize the dialog

### ISSUE THREAD

**Issue by davidBarbieri** [Skyost/RateMyApp#16]
Hi, i was wondering if there is any change some changes could be made to the Dialog structure:
The AlertDialog ButtonRow widget, is a row, which contains a padding, what is not exanded so it's always going to shrink around the action buttons, forcing them to align the right., would be nice to have the possibility to have some control over the buttons as well.

Cheers!

David

**Comment by davidBarbieri** [comment]
At the moment you can add any number of buttons as you want, but they'll all be stacked ad the right side cause of AlertDialog original styling, there is no way to have a button taking the fill width on the dialog, or place one button to the right and one to the left bottom corner of the dialog

**Comment by pmrajani** [comment]
@Skyost can we have option to set **Rate button on right side** and **No thanks button on left side**?

**Comment by Skyost** [comment]
@pmrajani That's the next milestone of the project I think, yes.

**Comment by grayknight2** [comment]
It would be awesome to have the possibility to round the dialog corners too

**Comment by Skyost** [comment]
@grayknight2 [Could be easy to do.](https://stackoverflow.com/a/53579501/3608831)

**Comment by grayknight2** [comment]
@Skyost Yes, I think It would be an improvement easy to implement
