### ISSUE TITLE
Android UI glitch - right overflow

### ISSUE THREAD

**Issue by teferio** [Skyost/RateMyApp#3]
Android UI glitch - right overflow

Device - Moto G 2nd Gen
Android - 6.0

`I/flutter (10171): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (10171): The following message was thrown during layout:
I/flutter (10171): A RenderFlex overflowed by 1.00 pixels on the right.
E/FA      (10171): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
I/flutter (10171): The overflowing RenderFlex has an orientation of Axis.horizontal.
I/flutter (10171): The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
I/flutter (10171): black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
I/flutter (10171): Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
I/flutter (10171): RenderFlex to fit within the available space instead of being sized to their natural size.
I/flutter (10171): This is considered an error condition because it indicates that there is content that cannot be
I/flutter (10171): seen. If the content is legitimately bigger than the available space, consider clipping it with a
I/flutter (10171): ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
I/flutter (10171): like a ListView.
I/flutter (10171): The specific RenderFlex in question is:
I/flutter (10171):   RenderFlex#0db86 relayoutBoundary=up8 OVERFLOWING
I/flutter (10171):   creator: Row ← Padding ← ButtonBar ← ButtonTheme ← Column ← IntrinsicWidth ← DefaultTextStyle ←
I/flutter (10171):   AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#cd0b1 ink renderer] ←
I/flutter (10171):   NotificationListener<LayoutChangedNotification> ← CustomPaint ← _ShapeBorderPaint ← ⋯
I/flutter (10171):   parentData: offset=Offset(4.0, 8.0) (can use size)
I/flutter (10171):   constraints: BoxConstraints(w=272.0, 0.0<=h<=Infinity)
I/flutter (10171):   size: Size(272.0, 48.0)
I/flutter (10171):   direction: horizontal
I/flutter (10171):   mainAxisAlignment: end
I/flutter (10171):   mainAxisSize: max
I/flutter (10171):   crossAxisAlignment: center
I/flutter (10171):   textDirection: ltr
I/flutter (10171):   verticalDirection: down
I/flutter (10171): ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
I/flutter (10171): ════════════════════════════════════════════════════════════════════════════════════════════════════`

![device-2019-05-20-080917](https://user-images.githubusercontent.com/42547420/58020891-7c17c280-7ad7-11e9-817e-6b1b98cd997c.png)

**Comment by Skyost** [comment]
Oops, I think it's more due to the [Warp](https://github.com/Skyost/rate_my_app/blob/master/lib/rate_my_app.dart#L116) than to the dialog in itself. I'm going to test if there is another solution.

**Comment by Skyost** [comment]
Fixed in 75c6d637903701f78c236f4a5fcfb98bd6f6bd57 as you can now use your own actions builder.
