### ISSUE TITLE
Version 0.6.0 doesn't work

### ISSUE THREAD

**Issue by crush3r** [Skyost/RateMyApp#39]
I use Flutter SDK v1.14.6 (Beta channel)
And I can't use the last version 0.6.0.
Running "flutter pub get" get an error:

Because every version of flutter_driver from sdk depends on pedantic 1.8.0+1 and rate_my_app >=0.6.0 depends on pedantic ^1.9.0, flutter_driver from sdk is incompatible with rate_my_app >=0.6.0.

**Comment by Skyost** [comment]
As stated in the message, this plugin is using `pedantic` v1.9.0 while `flutter_driver` is using `pedantic` v1.8.0. You either have to wait for `flutter_driver` to update their version or downgrade _Rate My App_ to `0.5.0+4`.
