### ISSUE TITLE
Dependency bug - wrong pedantic version

### ISSUE THREAD

**Issue by SteinFluss** [Skyost/RateMyApp#40]
Happens on flutter beta channel with version `0.6.0` of RateMyApp
```
Because every version of flutter_driver from sdk depends on pedantic 1.8.0+1 and rate_my_app >=0.6.0 depends on pedantic ^1.9.0, flutter_driver from sdk is incompatible with rate_my_app >=0.6.0.
```
I think this should be a pretty simple fix

**Comment by marklureal** [comment]
a similar issue  [https://github.com/Skyost/RateMyApp/issues/39](https://github.com/Skyost/RateMyApp/issues/39)

however, the version 0.5.0+4 disappears. Version 0.5.0+3 is available only.

**Comment by SteinFluss** [comment]
Is that plugin even needed? If it could be removed, we would not have to worry about versions.

**Comment by Skyost** [comment]
@SteinFluss I think that's what I'm gonna do yep.

**Comment by Skyost** [comment]
Done. Plop @crush3r.

**Comment by crush3r** [comment]
@Skyost Great, thank you!
