### ISSUE TITLE
Use Custom button in show rate dialog not working

### ISSUE THREAD

**Issue by sarawin008** [Skyost/RateMyApp#41]
I used normal rate dialog from your example 

this line that u comment out
// actionsBuilder: (_) => [], // This one allows you to use your own buttons.

when I custom my own button, it show dialog but when click rate or maybe later it doesn't go to store or even print  Clicked on "Rate" or anything it just dissapear. is that a bug?

this is my custom button code
----------------------------------------------------------
actionsBuilder: (_) => [
          FlatButton(
            child: Text(
              'Maybe Later',
              style: TextStyle(
                color: Colors.grey[300],
                fontFamily: 'NunitoExtraBold',
                fontSize: 15,
              ),
            ),
            onPressed: () async {              
              await _rateMyApp.callEvent(RateMyAppEventType.laterButtonPressed);
              Navigator.pop<RateMyAppDialogButton>(
                  context, RateMyAppDialogButton.later);
            },
          ),
          FlatButton(
            child: Text(
              'Rate Now',
              style: TextStyle(
                color: Color.fromRGBO(0, 121, 113, 1.00),
                fontFamily: 'NunitoExtraBold',
                fontSize: 15,
              ),
            ),
            onPressed: () async {
              await _rateMyApp.callEvent(RateMyAppEventType.rateButtonPressed);
              Navigator.pop<RateMyAppDialogButton>(
                  context, RateMyAppDialogButton.rate);
            },
          ),
        ],

**Comment by Skyost** [comment]
Can you please show me the full code ?
