### ISSUE TITLE
possibility to set the content of the dialog

### ISSUE THREAD

**Issue by silversquall** [Skyost/RateMyApp#43]
I'd like to have the possibility to replace title & message by whatever Widget of my choice

  Future<void> showStarRateDialog(
    BuildContext context, {
    String **title**,
    String **message**,

Thx.

**Comment by stanrisever** [comment]
firstly thanks for the package. Can you share sample code about sharedpreferences that shows how we should use it?

**Comment by Skyost** [comment]
@stanrisever https://github.com/Skyost/RateMyApp/blob/master/example/lib/main.dart

**Comment by silversquall** [comment]
@Skyost is there any plan to support my request ? thx.

**Comment by Skyost** [comment]
There is. But I don't know when at the moment. You're free to submit a pull request tho.

**Comment by silversquall** [comment]
@Skyost I have forked the project and implemented it, if you want to take a look.

**Comment by Skyost** [comment]
Will check this later. Please submit a pull request to see your changes implemented in the master branch.

**Comment by silversquall** [comment]
just did
