### ISSUE TITLE
Rating dialog not working

### ISSUE THREAD

**Issue by nicolasvahidzein** [Skyost/RateMyApp#45]
Hello when i use your star dialog, when i press on ok, nothing happens. Is this normal behavior?

I want to be able to use the star rating so i know what the user thinks of my app from inside the app. Thanks.

**Comment by Skyost** [comment]
You need to implement your own sending system. The intended behavior is to implement different actions based on the rating (for example : _1-3 stars_ = take him to your contact page, _4-5 stars_ = take him to the App / Play Store).

**Comment by Skyost** [comment]
Closed as inactive.
