### ISSUE TITLE
where to input customized parameters in the example project?

### ISSUE THREAD

**Issue by FisherWL** [Skyost/RateMyApp#52]
**Additional context**
This may sound stupid, but in the example with the RateMyAppBuilder(), I couldn't find a place to input/ replace my own parameters e.g. googlePlayIdentifier.
I tried to do a global search in these files, but it only pointed to README.md and core.dart

**Comment by Skyost** [comment]
`RateMyAppBuilder` has an option called [`rateMyApp`](https://github.com/Skyost/RateMyApp/blob/master/lib/src/widgets.dart#L20) where you can put your custom `RateMyApp` class instance (with your custom parameters) :wink:

**Comment by FisherWL** [comment]
Thanks for your quick response and great work! Appreciated.
Closing out this post.
