### ISSUE TITLE
plugin doesnt seem to work in test flight

### ISSUE THREAD

**Issue by crushman1** [Skyost/RateMyApp#53]
**Describe the bug**
The plugin works in debug mode but doesnt show up in test flight. Might that be because the app has not been published yet ?
**To Reproduce**
launch app on test flight and open 5 times.

**Expected behavior**
popup rate dialog box in production and debug modes.

**Comment by Skyost** [comment]
See #1 (and [this comment](https://github.com/Skyost/RateMyApp/issues/1#issuecomment-489042916) in particular). Does this help you ?

**Comment by Skyost** [comment]
Closed due to inactivity.
