### ISSUE TITLE
add support to show fade dialog using flutter animations plugin

### ISSUE THREAD

**Issue by kw2019ltd** [Skyost/RateMyApp#55]
hi
add support to show fade dialog 

Fade
The fade pattern is used for UI elements that enter or exit within the bounds of the screen, such as a dialog that fades in the center of the screen.

https://pub.dev/packages/animations#-installing-tab-

**Comment by Skyost** [comment]
Not sure about this one as it would mean a lot of rewrite and a plugin dependency for almost nothing more. But if you want, you can show your custom dialog using :

```
if(rateMyApp.shouldOpenDialog) {
  // Show your custom dialog here
}
```

Also see [Broadcasting events](https://github.com/Skyost/RateMyApp#broadcasting-events) if you want to be able to use Rate my app buttons (like `Rate` or `Maybe later`). You can also use the [predefined buttons](https://github.com/Skyost/RateMyApp/blob/master/lib/src/dialogs.dart#L282).
