### ISSUE TITLE
iOS requestReview is not checked against remind conditions

### ISSUE THREAD

**Issue by TomEversdijk** [Skyost/RateMyApp#56]
**Describe the bug**
On iOS with the default option ignoreIOS = false, the review dialog is only checked against it min-conditions (minDays & minLaunches). Once this condition is met, the iOS default review dialog will be display every time and it will not verify if the remind-conditions (remindDays & remindLaunches) are met. 

**To Reproduce**
1. Create a project with settings: `minDays: 0` & `minLaunches: 1`
2. Use `remindDays: 31` & `remindLaunches: 15` in the same project.
3. Start the app, the review dialog appears as expected, click on 'later'
4. Restart the app, the review dialog appears again. This is not expected as the remindConditions are not met. 

**Expected behavior**
I would expect to see the review dialog only after 31 days and 15 launches, not every launch.

**Screenshots**
/

**Smartphone :**
 - Device: iPhone6s
 - OS: iOS13.4.1

**Additional context**
Flutter --version
Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (4 weeks ago) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2.8.2

Apple is placing some hard limits on the review dialog itself as written here: https://developer.apple.com/documentation/storekit/skstorereviewcontroller/requesting_app_store_reviews

**How I think this should be fixed**
1. Ideal there would be a callback from Apple's native app rating dialog making it possible to invoke the `callEvent`-function in core.dart with the corresponding eventType.
2. As I have searched for callbacks and I couldn't find any useful information, I would suggest changing the `onEventOccurred`-fuctions in conditions.dart to not only check for the real eventType but also check for `RateMyAppEventType.iOSRequestReview`. This would fix it for the MinimumDaysCondition & MinimumAppLaunchesCondition. If I am correct, apple also checks if it can display the review dialog so the DoNotOpenAgainCondition is not useful in this case.
e.g.:
change: 
`if (eventType == RateMyAppEventType.laterButtonPressed)`
to: 
`if (eventType == RateMyAppEventType.laterButtonPressed || eventType == RateMyAppEventType.RateMyAppEventType.iOSRequestReview)`

**Comment by Skyost** [comment]
@TomEversdijk As you said, there is no way to handle a button click in this dialog. Your fix seems right to me, but what if the user taps on the "Rate" button ? The dialog will be opened again after 31 days and 15 launches, isn't it ?

**Comment by TomEversdijk** [comment]
I think this situation is handled by apple itself.

> The review prompt must not have been shown for a version of the app bundle that matches the current bundle version. This ensures that the user is not asked to review the same version of your app multiple times.

[https://developer.apple.com/documentation/storekit/skstorereviewcontroller/requesting_app_store_reviews](url)

**Comment by Skyost** [comment]
@TomEversdijk You're right. Anyway, I don't like their current review prompt system. They should have at least provided a callback.

**Comment by furkansarihan** [comment]
So we cannot use this package on ios right now?

**Comment by Skyost** [comment]
@furkansarihan It is perfectly usable on iOS. Feel free to test it by yourself :wink:
