### ISSUE TITLE
remindDays not working as expected in MinimumDaysCondition

### ISSUE THREAD

**Issue by SimeonZV** [Skyost/RateMyApp#57]
**Describe the bug**
The rate dialog may pop up too often not correctly respecting remindDays

**To Reproduce**
MinimumDaysCondition tracks and uses the baseLaunchDate for checking it in the isMet getter. Let's assume we set the remindDays = 2 and the user interacted with the app last time half year ago. It will save the baseLaunchDate in the shared preferences as a date from about half a year ago. If the user started using the app now and keeps pressing the "Remind Later" button, it will increment the baseLaunchDate by 2 days still keeping the popup dialogs opened immediately for a very long time.

**Expected behavior**
It's expected that the rate dialog doesn't popup earlier than in the remindDays after being closed last time.

**Additional context**
I would suggest that the MinimumDaysCondition should be split into two conditions. One, which deals just with minDays, should just use the launch date. The other one, probably called RemindDaysCondition, should use the last dialog close time and should use the remindDays in the isMet getter (not the case at the moment at all)

**Comment by Skyost** [comment]
Thanks for pointing this issue ! I think I have another solution. I could keep the current system but, I can just replace `baseLaunchDate` by something called `minimumDate`. This way, we could just update the `minimumDate` when user clicks on _Maybe later_ using the formula `minimumDate = now + remindLaunches` i.e. :

```dart
/// The minimum days condition.
class MinimumDaysCondition extends DebuggableCondition {
  /// Minimum days before being able to show the dialog.
  final int minDays;

  /// Days to add to the base date when the user clicks on "Maybe later".
  final int remindDays;

  /// The minimum date required to meet this condition.
  DateTime minimumDate;

  /// Creates a new minimum days condition instance.
  MinimumDaysCondition({
    @required this.minDays,
    @required this.remindDays,
  })  : assert(minDays != null),
        assert(remindDays != null);

  @override
  void readFromPreferences(SharedPreferences preferences, String preferencesPrefix) {
    minimumDate = DateTime.fromMillisecondsSinceEpoch(preferences.getInt(preferencesPrefix + 'minimumDate') ?? _now().millisecondsSinceEpoch);
  }

  @override
  Future<void> saveToPreferences(SharedPreferences preferences, String preferencesPrefix) {
    return preferences.setInt(preferencesPrefix + 'minimumDate', minimumDate.millisecondsSinceEpoch);
  }

  @override
  void reset() => minimumDate = _now();

  @override
  bool get isMet {
    return DateTime.now().isAfter(minimumDate);
  }

  @override
  bool onEventOccurred(RateMyAppEventType eventType) {
    if (eventType == RateMyAppEventType.laterButtonPressed || eventType == RateMyAppEventType.iOSRequestReview) {
      minimumDate = _now(Duration(days: remindDays));
      return true;
    }

    return false;
  }

  @override
  String get valuesAsString {
    return 'Minimum days : $minDays\nRemind days : $remindDays\nMinimum valid date : ${_dateToString(minimumDate)}';
  }

  /// Returns a formatted date string.
  String _dateToString(DateTime date) => date.day.toString().padLeft(2, '0') + '/' + date.month.toString().padLeft(2, '0') + '/' + date.year.toString();

  /// Returns the current date with the minimum days added.
  DateTime _now([Duration toAdd]) => DateTime.now().add(toAdd ?? Duration(days: minDays));
}
```

**Comment by SimeonZV** [comment]
It looks like a good solution and thanks for the fixing it so quickly!
