### ISSUE TITLE
Hide No Thanks Button

### ISSUE THREAD

**Issue by KevinYan12138** [Skyost/RateMyApp#58]
I want to know if it is possible to hide the "No Thanks" button in the dialog since tapping this button will hide the review dialog forever.

**Comment by Skyost** [comment]
Why don't you [check it](https://github.com/Skyost/RateMyApp/blob/master/lib/src/core.dart#L101) by yourself ?

**Comment by KevinYan12138** [comment]
> Why don't you [check it](https://github.com/Skyost/RateMyApp/blob/master/lib/src/core.dart#L101) by yourself ?

Sorry, correct me if I misunderstand your response. Do you mean there is already a method to do that?

**Comment by Skyost** [comment]
Yes. Just use the `actionsBuilder` parameter (and return for example `[RateMyAppRateButton(rateMyApp), RateMyAppLaterButton(rateMyApp)]` with `rateMyApp` being your `RateMyApp` instance).

**Comment by KevinYan12138** [comment]
> Yes. Just use the `actionsBuilder` parameter (and return for example `[RateMyAppRateButton(rateMyApp), RateMyAppLaterButton(rateMyApp)]` with `rateMyApp` being your `RateMyApp` instance).

Thank you so much for your response, and sorry for asking such a stupid question. Thank you, I will try that :)

**Comment by Skyost** [comment]
> Thank you so much for your response, and sorry for asking such a stupid question.

No problem, there's no stupid question. Tell me back if it has worked :wink:
