### ISSUE TITLE
Unable to launch app after upgrading to flutter 1.20

### ISSUE THREAD

**Issue by sderungs99** [Skyost/RateMyApp#63]
**Describe the bug**
Running the app fails after upgrading to flutter 1.20, and it complains about an error in the rate_my_app plugin. Following is the output:
flutter run
Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
 
Running pod install...                                              3.1s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           17.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    error: the following command failed with exit code 0 but produced no further output
    CompileC
    /Users/sascha/Library/Developer/Xcode/DerivedData/Runner-ghqosdadugvesdczfyvwpkytgzit/Build
    /Intermediates.noindex/Pods.build/Debug-iphonesimulator/rate_my_app.build/Objects-normal/x8
    6_64/RateMyAppPlugin.o
    /Users/sascha/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.1+6/ios/Classe
    s/RateMyAppPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.3.0/lib/src/stack.dart
    :69:13: Error: No named parameter with the name 'overflow'.
                overflow: overflow);
                ^^^^^^^^
    ../../flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.3.0/lib/src/stack.dart
    :73:9: Error: The getter 'overflow' isn't defined for the class '_RenderStack'.
     - '_RenderStack' is from 'package:convex_bottom_bar/src/stack.dart'
     ('../../flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.3.0/lib/src/stack.d
     art').
    Try correcting the name to the name of an existing getter, or defining a getter or field
    named 'overflow'.
        if (overflow == Overflow.visible || size.contains(position)) {
            ^^^^^^^^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone SE (2nd generation).

**To Reproduce**
1. Upgrade flutter to 1.20.x
2. Try to run the app

**Expected behavior**
App should start without errors

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: iOS

**Smartphone (please complete the following information):**
 - Device: iPhone SE (2nd generation)

**Additional context**
N/A

**Comment by Skyost** [comment]
How is it related to _RateMyApp_ ? The problem is :

```
../../flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.3.0/lib/src/stack.dart
:69:13: Error: No named parameter with the name 'overflow'.
overflow: overflow);
^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.3.0/lib/src/stack.dart
:73:9: Error: The getter 'overflow' isn't defined for the class '_RenderStack'.
- '_RenderStack' is from 'package:convex_bottom_bar/src/stack.dart'
('../../flutter/.pub-cache/hosted/pub.dartlang.org/convex_bottom_bar-2.3.0/lib/src/stack.d
art').
Try correcting the name to the name of an existing getter, or defining a getter or field
named 'overflow'.
```

(so it's [convex_bottom_bar](https://pub.dev/packages/convex_bottom_bar))

**Comment by sderungs99** [comment]
Yes, my bad :-( thank you for the quick answer!

**Comment by Skyost** [comment]
No problem @sderungs99 😉
