### ISSUE TITLE
Unhandled Exception: PlatformException(activity_is_null, Activity is null., null)

### ISSUE THREAD

**Issue by aleaforny** [Skyost/RateMyApp#66]
**Describe the bug**
When the RateMyApp is called, the dialog is not prompted at all and I get the following error : 
```
E/flutter (30220): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(activity_is_null, Activity is null., null)
E/flutter (30220): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
E/flutter (30220): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
E/flutter (30220): <asynchronous suspension>
E/flutter (30220): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (30220): #3      RateMyApp.isNativeReviewDialogSupported (package:rate_my_app/src/core.dart:96:62)
E/flutter (30220): #4      RateMyApp.showStarRateDialog (package:rate_my_app/src/core.dart:157:38)
```

**PLEASE NOTE** that this issue only occurs when `ignoreNativeDialog `is set to `false`. When this parameter is set to `true`, everything works as expected (with no change of the context).

RateMyApp is called after main() initialization, way after the widgets are painted.

**Smartphone (please complete the following information):**
 - Device: Galaxy A20e
 - OS: Android 9

**Additional context**
RateMyApp version used: `0.7.0`
Flutter doctor output: 
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18363.1016], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)
```

Thanks for the help

**Comment by Skyost** [comment]
It happens [here](https://github.com/Skyost/RateMyApp/blob/master/android/src/main/kotlin/fr/skyost/rate_my_app/RateMyAppPlugin.kt#L41). It means that either the main activity has not been attached or has been detached.

**Comment by aleaforny** [comment]
Thanks @Skyost for this awesome plugin.

Do you think it could be related to the fact that I'm launching the app using `flutter run` (this is not the app installed from the PlayStore)?

**Comment by Skyost** [comment]
@aleaforny No, it should work the same way. I'm also using `flutter run` during my tests (but it works for me).
Does it happen at every launch ? Would it be possible to see your code ?

**Comment by aleaforny** [comment]
Yup, every launch. 

Hope these fragments of code can help (tried to remove as much as useless code for this investigation as I could):
```
class DashboardPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _DashboardPageState();
  }
}

class _DashboardPageState extends State<DashboardPage> {
  RateMyApp _rateMyApp = RateMyApp(
    preferencesPrefix: 'rateMyApp_',
    minDays: 7,
    minLaunches: 10,
    remindDays: 7,
    remindLaunches: 10,
    googlePlayIdentifier: "xxx",
    appStoreIdentifier: "xxx"
   );
  [...]

  @override
  void initState() {
    super.initState();
    [...]
  }

  [...]
  void _rateMyApp(BuildContext thisContext) async {
      await _rateMyApp.reset(); //TODO: Disable this line before going production!
      _rateMyApp.init().then((_) {
        if (_rateMyApp.shouldOpenDialog) {
          _rateMyApp.showStarRateDialog(
            thisContext,
            title: 'Notez notre app !', // The dialog title.
            message: 'Vous aimez notre app ?\nSVP prenez quelques instants pour donner votre avis :', // The dialog message.
            actionsBuilder: (context, stars) { // Triggered when the user updates the star rating.
              return [ // Return a list of actions (that will be shown at the bottom of the dialog).
                FlatButton(
                  child: Text('Plus tard'),
                  onPressed: () async {
                    await _rateMyApp.callEvent(RateMyAppEventType.laterButtonPressed);
                    Navigator.of(context).pop();
                  },
                ),
                SizedBox(width: 5.0),
                FlatButton(
                  child: Text('OK'),
                  onPressed: () async {
                    print('Thanks for the ' + (stars == null ? '0' : stars.round().toString()) + ' star(s) !');
                    await _rateMyApp.callEvent(RateMyAppEventType.rateButtonPressed);
                    Navigator.pop<RateMyAppDialogButton>(context, RateMyAppDialogButton.rate);
                  },
                ),
              ];
            },
            ignoreNativeDialog: false, // TODO: bug in progress:  https://github.com/Skyost/RateMyApp/issues/66
            dialogStyle: DialogStyle( // Custom dialog styles.
              titleAlign: TextAlign.center,
              messageAlign: TextAlign.center,
              messagePadding: EdgeInsets.only(bottom: 20),
            ),
            starRatingOptions: StarRatingOptions(), // Custom star bar rating options.
          );
        }
      });
  }

 [...]

  @override
  Widget build(BuildContext context) {
    WidgetsBinding.instance.addPostFrameCallback((_) => _rateMyApp(context));
    return ScopedModelDescendant(
      builder: (BuildContext context, Widget child, GlobalApp global) {
        return Container(
          child: Scaffold(
            body: _buildBodyContent(context),
            [...]
          ),
        );
      },
    );
  }
}
```

FYI, I'm trying to call RateMyApp on a specific screen, using addPostFrameCallback so that it shall be called whenever the build is done.

Thanks again!

**Comment by Skyost** [comment]
Thanks. If I could give you one advice : don't show call `_rateMyApp` in the `build` method, because it can be called very often during the widget lifecycle. Just put the following piece of code in your `initState` method and it will work the same way (but will not get called again and again during each build) :

```dart
WidgetsBinding.instance.addPostFrameCallback((_) => _rateMyApp(context));
```

**Comment by saigkl** [comment]
@Skyost Even I face this problem, I'm calling the `rateMyApp` in `initState` only,  Still getting the same error on android. On iOS, this works fine. Any workaround or fixes?

**Comment by Skyost** [comment]
@saigkl I don't know what is causing this error, so no. Not for the moment.

**Comment by Cortrano** [comment]
I have same error on android :c Any solutions? I can't even .launchStore;

**Comment by Skyost** [comment]
Would you please send me your code @Cortrano ?

**Comment by horgag** [comment]
same issue here. 

Here is my code:

```
class SettingsBloc extends Bloc<SettingsEvent, SettingsState> {
  SettingsBloc() : super(SettingsListState());
  
  @override
  Stream<SettingsState> mapEventToState(SettingsEvent event) async* {
    if (event is RateAppPressed) {
      yield SettingsLoadingState();
      try {
        var rateMyApp = RateMyApp();
        await rateMyApp.init();
        yield RateAppInitialized(rateMyApp);
      } catch (e) {
        print(e.toString());
        yield SettingsErrorState(errorString: e.toString());
        Crashlytics.instance.recordError(e, e.stackTrace);
        print(e.stackTrace.toString());
      }
    }
  }
}
```

```
class SettingsScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        Navigator.popUntil(context, (route) => route.isFirst);
        return false;
      },
      child: Stack(
        children: <Widget>[
          TennerBackground(image: TennerImages.blue_gradient),
          Scaffold(
            backgroundColor: Colors.transparent,
            appBar: AppBar(
              title: Text("Settings"),
            ),
            body: TennerTextScreenSafeArea(
              child: BlocProvider<SettingsBloc>(
                create: (context) => SettingsBloc(),
                child: BlocListener<SettingsBloc, SettingsState>(
                  listener: (context, state) {
                    if (state is SettingsErrorState) {
                      TennerHelpers.showErrorSnackbar(message: state.errorString, context: context);
                    } else if (state is RateAppInitialized) {
                      state.rateMyApp.showRateDialog(
                        context,
                        title: 'Rate this app',
                        message: 'If you like this app, please take a minute to review it. Your feedback is really valuable to both us and other users. Thank you!',
                        rateButton: 'RATE',
                        noButton: 'NO THANKS',
                      );
                    }
                  },
                  child: BlocBuilder<SettingsBloc, SettingsState>(
                    builder: (context, state) {
                      if (state is SettingsLoadingState) {
                        return Center(
                          child: CircularProgressIndicator(),
                        );
                      } else {
                        return _settingsList(context);
                      }
                    },
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _settingsList(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: <Widget>[
          SettingMenuItem(
            title: "Rate the app",
            onTap: () => BlocProvider.of<SettingsBloc>(context).add(RateAppPressed()),
          ),
        ],
      ),
    );
  }
}

```

**Comment by Cortrano** [comment]
Maybe it associated with flutter update? I noticed, that some android native plugins have same errors with PlatformException

**Comment by Skyost** [comment]
@Cortrano Well, it's related to [`ActivityAware`](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/activity/ActivityAware.html). The activity has either been detached or not even been attached. I need to do further testings but I fail to reproduce this bug.

**Comment by ming290496** [comment]
Hi, it got this issue and I think I know how to resolve the problem. You need to migrate your app to the Android Embedding V2. I just migrate my app to Android embedding v2 by following this step [https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects](link). It actually works now.

**Comment by Skyost** [comment]
Thank you @ming290496 ! Can you confirm that it works for you @aleaforny @saigkl @Cortrano @horgag ?

▶ https://github.com/flutter/flutter/issues/59556

**Comment by attex** [comment]
Hi, i got the same issue but i cant migrate to Android embedding v2 cause i need the FlutterFragmentActivity in my MainActivity.kt.

Do you have other suggestions?

**Comment by Skyost** [comment]
@attex `io.flutter.app.FlutterFragmentActivity` has been replaced by `io.flutter.embedding.android.FlutterFragmentActivity`.

**Comment by PritamSangani** [comment]
> Hi, I got this issue and I think I know how to resolve the problem. You need to migrate your app to the Android Embedding V2. I just migrate my app to Android embedding v2 by following this step [https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects](link). It actually works now.

I followed the steps listed on this page to migrate my app to Android Embedding V2. However, I am still getting an exception thrown:

`Unhandled Exception: PlatformException(com.google.android.play.core.internal.aq, Failed to bind to the service., null)`

**Comment by Skyost** [comment]
@PritamSangani Can you post the full stacktrace please ?

**Comment by PritamSangani** [comment]
Here it is @Skyost 
```
I/PlayCore(13766): UID: [10157]  PID: [13766] ReviewService : requestInAppReview (com.bhujmandir.vachanamrut)
I/PlayCore(13766): UID: [10157]  PID: [13766] ReviewService : Initiate binding to the service.
I/PlayCore(13766): UID: [10157]  PID: [13766] ReviewService : Failed to bind to the service.
E/flutter (13766): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(com.google.android.play.core.internal.aq, Failed to bind to the service., null)
E/flutter (13766): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
E/flutter (13766): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
E/flutter (13766): <asynchronous suspension>
E/flutter (13766): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (13766): #3      RateMyApp.launchNativeReviewDialog (package:rate_my_app/src/core.dart:106:16)
E/flutter (13766): #4      RateMyApp.showStarRateDialog (package:rate_my_app/src/core.dart:169:13)
E/flutter (13766): #5      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (13766): #6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (13766): #7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (13766): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (13766): #9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (13766): #10     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (13766): #11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (13766): #12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (13766): #13     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
E/flutter (13766): #14     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (13766): #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (13766): #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (13766): #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (13766): #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (13766): #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (13766): #20     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter (13766): #21     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (13766): #22     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (13766): #23     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (13766): #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (13766): #25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (13766): #26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (13766): 
```

**Comment by PritamSangani** [comment]
@Skyost Have you had the chance to take a look at this?

**Comment by Skyost** [comment]
@PritamSangani I took a quick look, but I will not have the time to really work on it before (at least) friday, sorry. Looking quickly at your stacktrace, there seems to be a problem with Google Play / GMS. Maybe one of them is not installed or something like that ? (But even in that case, an error like this should not occur)

**Comment by Skyost** [comment]
I'm gonna open a separate issue for you @PritamSangani.

**Comment by FetFrumos** [comment]
I have same issue on android. I running this [example app](https://github.com/Skyost/RateMyApp/tree/master/example).

`E/MethodChannel#rate_my_app(21559): Failed to handle method call
E/MethodChannel#rate_my_app(21559): kotlin.KotlinNullPointerException
E/MethodChannel#rate_my_app(21559): 	at fr.skyost.rate_my_app.RateMyAppPlugin.onMethodCall(RateMyAppPlugin.kt:64)
E/MethodChannel#rate_my_app(21559): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#rate_my_app(21559): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#rate_my_app(21559): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#rate_my_app(21559): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#rate_my_app(21559): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#rate_my_app(21559): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#rate_my_app(21559): 	at android.app.ActivityThread.main(ActivityThread.java:6523)
E/MethodChannel#rate_my_app(21559): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#rate_my_app(21559): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#rate_my_app(21559): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)`

I tried changing the package id in android manifest (to existing one) but i still get this error.
Please check it. I need your plugin.

**Comment by tiramisujin** [comment]
For those who encounter the same problem but not ready yet to migrate your project to Android Embedding v2, the solution below works for me, but we need to amend the source package's codes.

Look into the package, open file RateMyAppPlugin.kt, replace the registerWith function with below
`fun registerWith(registrar: Registrar) {
            val instance = RateMyAppPlugin()
            instance.init(registrar)
            instance.channel = MethodChannel(registrar.messenger(), "rate_my_app")
            instance.channel.setMethodCallHandler(instance)
        }`

And finally, add below function after variables declaration
`fun init(registrar: Registrar) {
        activity = registrar.activity()
        context = registrar.context()
    }`

That's it.

**Comment by Skyost** [comment]
@FetFrumos That's not the same error. Are you providing a null value to `googlePlayIdentifier` ?

**Comment by FetFrumos** [comment]
@Skyost - thank you very much. I added googlePlayIdentifier and it working.

**Comment by skykz** [comment]
Same error 

> Unhandled Exception: PlatformException(activity_is_null, Activity is null., null)

**Comment by attex** [comment]
> @attex `io.flutter.app.FlutterFragmentActivity` has been replaced by `io.flutter.embedding.android.FlutterFragmentActivity`.

This is causing all plugins to throw an error "No implementation found for method .." 
As researched FragmentActivity is deprecated as well. So `FlutterActivity` does the job!

**Comment by Skyost** [comment]
@attex Good to know :wink: (I wasn't using `FlutterFragmentActivity` so I wasn't that sure)
