### ISSUE TITLE
Does this plugin actually rate the app?

### ISSUE THREAD

**Issue by attex** [Skyost/RateMyApp#71]
Hi there, 

is this plugin actually rating my app in the app store or does it only give the option to call the start dialog and forward the user to the playstore or appstore?

Kind regards

**Comment by baraaaljabban** [comment]
I was acutely looking for an answer for the same question 
I have app in production and the rating from inside the app dose not reflecting in app store ratings so would please tell us more about it @Skyost  ?

**Comment by Skyost** [comment]
Depends. If you're using the native dialog, then your users are going to rate your app from within it. Otherwise, it only takes them to the corresponding Store (by default).
