### ISSUE TITLE
It is not opening App Store For IOS

### ISSUE THREAD

**Issue by FL-K** [Skyost/RateMyApp#73]
**Describe the bug**
After executing the method
Future<void> launchStore() => RateMyApp._channel.invokeMethod('launchStore', {
        'appId': storeIdentifier,
      });

and having set properly appStoreIdentifier, app store is not opened to prompt for a review

**To Reproduce**

Easy, just execute the following anywhere you want:

```
RateMyApp _rateMyApp = RateMyApp(
  preferencesPrefix: 'rateMyApp_',
  minDays: 7,
  minLaunches: 10,
  remindDays: 7,
  remindLaunches: 10,
  appStoreIdentifier: 'putsomeappidhere',
);

_rateMyApp.launchStore();
```

**Expected behavior**
It is expected that user is redirected to app store and prompted to review that app, currently nothing happens!

**Screenshots**

![Screenshot 2020-09-10 at 12 20 46](https://user-images.githubusercontent.com/44264012/92717346-5a8fb980-f360-11ea-80ad-94767c852361.png)

I tried to debug your plugin RateMyAppPlugin.m, and I see that canOpenUrl returns always false, and then code to open store is not executed....

**Comment by Skyost** [comment]
Well, if `canOpenUrl` is always returning `false`, there's pretty much nothing you can do. Does [this answer](https://stackoverflow.com/a/34331058/3608831) work for you ?

**Comment by FL-K** [comment]
@Skyost thanks first for reply

I have this in my info.plist, so yes I have itms there

	<array>
	      // other stuff
		<string>itms</string>
	</array>

And still the dialog does not open both in emulator ios and real IPHONE device


Any thoughts of this? Does it work for you on ios...

**Comment by kristijorgji** [comment]
Same issue.

@Skyost


Can you change the plugin code to open at least the website if that returns false and cannot open app store directly.

Or return a proper value from this channel call, so we know if error happened or not, and maybe retry ourselves in the flutter code to open web

**Comment by Skyost** [comment]
@kristijorgji Good idea, I'm gonna do that.

**Comment by kristijorgji** [comment]
> @kristijorgji Good idea, I'm gonna do that.

Great thanks for that. But also is weird why it is always returning false, the canOpen call actually... also having added in query scheme both itms and itms-apps

But at least the suggested change should give us, the consumers a second chance to handle things in some other way when the plugin cannot open the ios store.

And for the android store works always great. Great job with the plugin

**Comment by Skyost** [comment]
>But also is weird why it is always returning false, the canOpen call actually

Agreed. Developing on iOS can be painful sometimes.

>But at least the suggested change should give us, the consumers a second chance to handle things in some other way when the plugin cannot open the ios store.

Yes, as you said, you could always try to use something like `url_launcher` if it fails with `launchStore`.

>And for the android store works always great. Great job with the plugin

Top, thanks 😁

**Comment by Skyost** [comment]
I think I've fixed this using what @kristijorgji advised me to do. Could you please try the new implementation @FL-K and tell me if it works for you ?

You can try the new version with :

```yaml
dependencies:
  rate_my_app:
    git:
      url: https://github.com/Skyost/RateMyApp
      ref: master
```

(in your `pubspec.yml`)

**Comment by kristijorgji** [comment]
I can try that too, but aren't you gonna publish e new version ? Or you want us to test first then publish the new version

**Comment by Skyost** [comment]
@kristijorgji The new version is ready to be published, you just have to confirm me that it contains the required changes.

**Comment by kristijorgji** [comment]
error: The named parameter 'ignoreIOS' isn't defined. (undefined_named_parameter at [single_app] lib/utils/prompt_rate_dialog.dart:101)

Is it possible to revert this option back make it backward compatible ?

That error is shown when showing the star dialog, and want to ignore the default ios to be shown

**Comment by kristijorgji** [comment]
Ok for some reason safary complains and cannot open the url
https://itunes.apple.com/app/id\(appId!)")

which is really weird (appid is repleaced with the real app id)

<img width="345" alt="Screenshot 2020-09-13 at 16 25 50" src="https://user-images.githubusercontent.com/15630854/93020564-14478e00-f5de-11ea-8748-a4ac0a8895e8.png">

**Comment by Skyost** [comment]
@kristijorgji Thanks for testing. So Safari is telling you that https://itunes.apple.com/app/id\(appId!) (with `\(appId!)` being your app id) is an invalid address ?

**Comment by kristijorgji** [comment]
> @kristijorgji Thanks for testing. So Safari is telling you that [https://itunes.apple.com/app/id\(appId!)](https://itunes.apple.com/app/id%5C(appId!)) (with `\(appId!)` being your app id) is an invalid address ?

Yes exactly, I tried inside IOS simulator

**Comment by Skyost** [comment]
@kristijorgji Oh you're using a simulator. I think that's the problem (see [this](https://stackoverflow.com/a/13659108/3608831)).

**Comment by kristijorgji** [comment]
The app store in old version of plugin was not being opened also in a real device.

yes know safari is not opening that page in emulator.... but that is one website not the app store itself the link at  https://itunes.apple.com/app/id(appId!) (with

**Comment by Skyost** [comment]
@kristijorgji 

> The app store in old version of plugin was not being opened also in a real device.

You mean, using `rateMyApp.launchStore()` ? Well at least, you now have an alternative if this method is failing.

> yes know safari is not opening that page in emulator.... but that is one website not the app store itself the link at https://itunes.apple.com/app/id(appId!) (with

I was precisely speaking about that.

**Comment by gtu-myowin** [comment]
Hi @Skyost, What is the solution to this issue? I am having the same issue, and `await _rateMyApp.launchStore();` is launching an incorrect URL in Safari. The url it tried to open was `https://itunes.apple.com/app/idcom.myapp.app`
