### ISSUE TITLE
Running on mac: The plugin `rate_my_app` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.

### ISSUE THREAD

**Issue by RafaelR7** [Skyost/RateMyApp#77]
Hi, everything is working fine on Android, but I was going to test on ios, when I do `flutter packages get`, it show the message: 

`The plugin rate_my_app requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.`

Do I really need to make that migration?

Thanks in advance

**Comment by Skyost** [comment]
@RafaelR7 :

> Do I really need to make that migration?

Yes. If you're not ready to do it, you should stay on `0.6.1+7`.
