### ISSUE TITLE
showStarRateDialog doesn't open Google Play Store page

### ISSUE THREAD

**Issue by stepanov-standy** [Skyost/RateMyApp#78]
**Describe the bug**
showStarRateDialog doesn't open Google Play Store page. On the other hand showRateDialog opens Google Play Store page as expected on the same configuration.

UPD: Looks like the problem is in actionsBuilder. When I add custom actionsBuilder to showRateDialog, it stops open Google Play Store page too.

actionsBuilder: (context) {
        return [
          FlatButton(
            child: Text(Localization.of(context).later),
            onPressed: () async {
              rateMyApp.callEvent(RateMyAppEventType.laterButtonPressed);
              Navigator.pop<RateMyAppDialogButton>(
                  context, RateMyAppDialogButton.rate);
            },
          ),
          FlatButton(
            child: Text(Localization.of(context).rate),
            onPressed: () async {
              await rateMyApp.callEvent(RateMyAppEventType.rateButtonPressed);
              Navigator.pop<RateMyAppDialogButton>(
                    context, RateMyAppDialogButton.rate);
            },
          ),
        ];
      },

**To Reproduce**
Follow instructions to add rate_my_app library to flutter project.
Call showStarRateDialog.
Dialog is closed without showing Google Play Store page.

**Expected behavior**
Google Play Store page should be displayed.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a, Xioami Mi5
 - OS: Android 11, Android 9

**Comment by Skyost** [comment]
@stepanov-standy You have to manually call `rateMyApp.launchStore()` if you want to open the store page in a custom action widget.

**Comment by stepanov-standy** [comment]
Thanks! Should we add this line of code to this [section](https://pub.dev/packages/rate_my_app#using-it-in-your-code) on pub.dev?

**Comment by Skyost** [comment]
I don't think so, as it is only an example, and it only that is only there to suggest you what to do, nothing more.
