### ISSUE TITLE
Native Rating Dialog implementation

### ISSUE THREAD

**Issue by sivaperumal644** [Skyost/RateMyApp#80]
**Describe the bug**
I have been using this plugin for rating, it was working fine. And now that this plugin supports Google's In-App-Review, I implemented it, but I couldn't see the rating dialog still now. I know that this will only work if the app is in the play-store and my app is in the playstore. I tested this many times and still I couldn't see Google's In-App-Review.

This is my code.

rate_my_app.dart

```
class RateApp {
  static giveRate(BuildContext context) {
    RateMyApp rateMyApp = RateMyApp(
      preferencesPrefix: 'rateMyApp_',
      minDays: 0,
      minLaunches: 0,
      remindDays: 7,
      remindLaunches: 20,
      googlePlayIdentifier: packageName(),
      appStoreIdentifier: iosIdentifier(),
    );

    rateMyApp.init().then((_) async {
      if (rateMyApp.shouldOpenDialog) {
        if (await rateMyApp.isNativeReviewDialogSupported) {
          rateMyApp.showRateDialog(
            context,
            title: StringResource.RATE_THIS_APP, // The dialog title.
            message:
                StringResource.RATE_THIS_APP_MESSAGE, // The dialog message.
            rateButton: StringResource.RATE, // The dialog "rate" button text.
            noButton: StringResource.NO_THANKS, // The dialog "no" button text.
            laterButton:
                StringResource.MAYBE_LATER, // The dialog "later" button text.
            ignoreNativeDialog:
                false, // Set to false if you want to show the Apple's native app rating dialog on iOS or Google's native app rating dialog (depends on the current Platform).
            dialogStyle: DialogStyle(), // Custom dialog styles.
          );
        }
      }
    });
  }
```
And in my initial screen's build method I call this.

`RateApp.giveRate(context);`

**Expected behavior**
The expected behavior is to show Google's In-App-Rating for android and IOS Native rating dialog for ios.

**Smartphone (please complete the following information):**
 - Device: Nokia 6.2
 - OS: 10.0

**Comment by Skyost** [comment]
Does it work if you pass `ignoreNativeDialog` to `true` ? Also please check the result of `rateMyApp.shouldOpenDialog` and `rateMyApp.isNativeReviewDialogSupported`.

**Comment by kreativityapps** [comment]
I can also reproduce it.

From logs:
`I/PlayCore(16769): UID: [10809]  PID: [16769] ReviewService : requestInAppReview ()
I/PlayCore(16769): UID: [10809]  PID: [16769] ReviewService : Initiate binding to the service.
I/PlayCore(16769): UID: [10809]  PID: [16769] ReviewService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.inappreviewservice.InAppReviewService})
I/PlayCore(16769): UID: [10809]  PID: [16769] ReviewService : linkToDeath
I/PlayCore(16769): UID: [10809]  PID: [16769] OnRequestInstallCallback : onGetLaunchReviewFlowInfo
I/PlayCore(16769): UID: [10809]  PID: [16769] ReviewService : Unbind from service.`

`ignoreNativeDialog ` set to `true` works, but with `false` no dialog is shown.

**Comment by DenchikBY** [comment]
> I can also reproduce it.
> 
> From logs:
> 
> > I/PlayCore(16769): UID: [10809]  PID: [16769] ReviewService : requestInAppReview ()
> > I/PlayCore(16769): UID: [10809]  PID: [16769] ReviewService : Initiate binding to the service.
> > I/PlayCore(16769): UID: [10809]  PID: [16769] ReviewService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.inappreviewservice.InAppReviewService})
> > I/PlayCore(16769): UID: [10809]  PID: [16769] ReviewService : linkToDeath
> > I/PlayCore(16769): UID: [10809]  PID: [16769] OnRequestInstallCallback : onGetLaunchReviewFlowInfo
> > I/PlayCore(16769): UID: [10809]  PID: [16769] ReviewService : Unbind from service.
> 
> `ignoreNativeDialog ` set to `true` works, but with `false` no dialog is shown.

Same for me, isNativeReviewDialogSupported return true, but there is no dialog

**Comment by Skyost** [comment]
@sivaperumal644 @kreativityapps @DenchikBY See #64 guys.

**Comment by DenchikBY** [comment]
> @sivaperumal644 @kreativityapps @DenchikBY See #64 guys.

Thanks for explanation. Mb you should add this into description to don't have same questions any more.

**Comment by Skyost** [comment]
@DenchikBY Yeah I know… I pinned it yersteday 😁
