### ISSUE TITLE
Google app rejected

### ISSUE THREAD

**Issue by joesnarky** [Skyost/RateMyApp#83]
Google has rejected an app of mine for using this library with the reason
"Prompt users to leave a rating and review from within your app with the in-app review API"

I believe it is because I added some code list this.

if (stars > 3) {
     rateMyApp.launchStore();
} else {
  /* request to send feedback email */
}

Not a bug but a warning.

**Comment by Skyost** [comment]
You may need to pass `ignoreNative` to `false`.

**Comment by joesnarky** [comment]
I think they have an issue with performing a different action if the rating is not high enough. Here I was trying to filter lower ratings and direct users to a popup dialog to submit a feedback email instead. I could be wrong because google is always vague when reporting issues.

**Comment by Skyost** [comment]
Yes, you're [totally right](https://appradar.com/blog/ask-users-leave-review-in-app-stores#fraudulent-methods-to-gain-more-app-store-reviews).
