### ISSUE TITLE
What happens when the app is updated?

### ISSUE THREAD

**Issue by RafaelR7** [Skyost/RateMyApp#84]
Hi, I have an app released on the app stores, and saw that the same user has written more than one review already, I wonder how the package reacts when the app is updated (I updated the app once, since I first released a version with the package), it resets the launches and min days?
thanks

**Comment by Skyost** [comment]
@RafaelR7 An user can't write different reviews, but he is totally able to edit its previous review. As for your question, well, the plugin stores its data in `SharedPreferences` (on Android), so it's persistant between updates.
