### ISSUE TITLE
Handle set condition "Not Now" button clicked for IOS Native Dialog

### ISSUE THREAD

**Issue by dewadhitya** [Skyost/RateMyApp#89]
**Describe the bug**
I created a rating dialog like this code :
```
rateMyApp.showRateDialog(
    context,
    title: "How would you rate our app experience?",
    message: "Let us know how the app works for you.",
    rateButton: 'RATE',
    noButton: 'NO THANKS',
    laterButton: 'MAYBE LATER',
    listener: (button) {
      if (button == RateMyAppDialogButton.later) {
        //logic -- will show again
      } else if (button == RateMyAppDialogButton.no ||
          button == RateMyAppDialogButton.rate) {
        //logic -- not show again
      }
      return true;
    },
);
```

If it runs on an Android device the logic works properly. For example: if I tap the "No Thanks" button the dialog will not show, if I tap the "Later" button the dialog will show again (based on the condition I made). But on an IOS device, if I tap the "Not Now" button, it will not pass the logic that I made.

**Expected behavior**
How to make pass the logic I made for IOS native dialog if I tap "Not Now" button. From the code below : 
```
listener: (button) {
    if (button == RateMyAppDialogButton.later) {
    //logic -- will show again
    } else if (button == RateMyAppDialogButton.no ||
        button == RateMyAppDialogButton.rate) {
    //logic -- not show again
    }
    return true;
},
```

**Screenshots**
<img width="429" alt="Screen Shot 2020-12-09 at 18 41 00" src="https://user-images.githubusercontent.com/27942767/101623379-548aa100-3a53-11eb-8f11-b0d20abe8084.png">
<img width="363" alt="Screen Shot 2020-12-09 at 18 49 25" src="https://user-images.githubusercontent.com/27942767/101623404-5ce2dc00-3a53-11eb-9c45-db9791f4a8ad.png">

**Smartphone (please complete the following information):**
 - Device: IOS Emulator, Android Emulator, Xiaomi Redmi Note 8 Pro
 - OS: Android 10 (Xiaomi Redmi Note 8 Pro)

**Comment by Skyost** [comment]
In short : you can't. Apple doesn't provide any callback for its native dialog :(

**Comment by dewadhitya** [comment]
Thanks for your information.

**Comment by Skyost** [comment]
You're welcome.
