### ISSUE TITLE
Button style

### ISSUE THREAD

**Issue by shinyo17** [Skyost/RateMyApp#91]
Hello I'm using your nice 'RateMyApp'!
It performs good! But I want to change the default text color.
I can change the title's color by titleStyle, But I don't know how to the button's color.
If package has the button color change feature, plz give me the way how to change the button color.
Or If package do not have the button color change feature, I will ask you to add this feature.
Thank you!

```
rateButton: 'rate my app',
            noButton: 'no thanks',
            laterButton: 'later!',
            listener: (button) {
              switch (button) {
                case RateMyAppDialogButton.rate:
                  print('Clicked on "Rate".');
                  break;
                case RateMyAppDialogButton.later:
                  print('Clicked on "Later".');
                  break;
                case RateMyAppDialogButton.no:
                  print('Clicked on "No".');
                  break;
              }
              return true; 
            },
```

**Comment by Skyost** [comment]
You can implement your custom buttons using the `actionsBuilder` parameter.

**Comment by shinyo17** [comment]
thank you! The answer was helpful to me.

**Comment by Skyost** [comment]
Cool then 😉
