### ISSUE TITLE
Display native dialog after user clicks "Rate" button

### ISSUE THREAD

**Issue by Aulig** [Skyost/RateMyApp#94]
I'd like the flutter dialog with my title and message to appear. Then when the user clicks "Rate", the native Android/iOS review dialog opens. Currently, the closest I got was with ignoreNativeDialog: true, but that opens the PlayStore when clicking "Rate" instead of using the native review dialog. With ignoreNativeDialog: false, it directly opens the native rating dialog.In that case there's no way to remind the user again later, right?

**Comment by Aulig** [comment]
Oh I just saw your comment on another issue that the native dialog shouldnt be opened as a result of an action as it might not be shown. Is there a way to test if it would be shown and instead open the store only if the native dialog couldnt be displayed?

**Comment by Skyost** [comment]
@Aulig As you can read [here](https://developer.android.com/guide/playcore/in-app-review/kotlin-java#launch-review-flow) :

```
The API does not indicate whether the user reviewed or not, or even whether the review dialog was shown.
```

Therefore, the answer is no. And it's the same answer for iOS (sadly) 😔

**Comment by Aulig** [comment]
That's unfortunate, sorry for wasting your time. Let's hope they add support for that soon.

Anyways I appreciate this library a lot, it's very useful :)

**Comment by Skyost** [comment]
@Aulig You're welcome 😉👍
