### ISSUE TITLE
Exception when startin RateMyApp for native ratings

### ISSUE THREAD

**Issue by Arcturus5404** [Skyost/RateMyApp#96]
**Describe the bug**
When calling the showRateDialog method with ignoreNativeDialog: false, an exception is being thrown:

E/flutter ( 6167): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Future<bool?>' is not a subtype of type 'FutureOr<bool>' in type cast
E/flutter ( 6167): #0      RateMyApp.showRateDialog (package:rate_my_app/src/core.dart:128:46)
E/flutter ( 6167): #1      _StartScreenState._showRateMyApp (package:paintmaster/screens/start_screen.dart:342:24)
E/flutter ( 6167): #2      _StartScreenState.initState.<anonymous closure> (package:paintmaster/screens/start_screen.dart:335:9)
E/flutter ( 6167): <asynchronous suspension>

**To Reproduce**
1. Call the method, see an exception

**Expected behavior**
No exceptions, I am not sure if the rate dialog works right now

**Screenshots**
The app runs fine though

**Comment by Arcturus5404** [comment]
I think the fix is simple. The as `Future<bool>` should be `Future<bool?>`

**Comment by Skyost** [comment]
You're right, thanks for reporting !
