### ISSUE TITLE
Apple rejection

### ISSUE THREAD

**Issue by simo9900** [Skyost/RateMyApp#97]
I've got this message from apple when deploying my app

Guideline 5.6.1 - Legal - App Store Reviews

We noticed that your app includes content and features that can manipulate user reviews for your app on the App Store. Specifically, your app filters user reviews and only directs users who intend to rate your app 4 - 5 stars to complete a rating on the App Store.

```
RateMyApp rateMyApp = RateMyApp(
    preferencesPrefix: 'rateMyApp_',
    minDays: 4,
    minLaunches: 6,
    remindDays: 4,
    remindLaunches: 6,
    googlePlayIdentifier: Consts.googlePlayIdentifier,
    appStoreIdentifier: Consts.appStoreIdentifier,
  );


RateMyAppBuilder(
            rateMyApp: rateMyApp,
            onInitialized: (context, rateMyApp) {
              // Called when Rate my app has been initialized.
              // See the example project on Github for more info.

              // setState(() =>
              // builder = (context) => ContentWidget(rateMyApp: rateMyApp));

              // rateMyApp.reset();
              rateMyApp.conditions.forEach((condition) {
                if (condition is DebuggableCondition) {
                  print(condition
                      .valuesAsString); // We iterate through our list of conditions and we print all debuggable ones.
                }
              });

              print('Are all conditions ccmet ? ' +
                  (rateMyApp.shouldOpenDialog ? 'Yes' : 'No'));

              if (rateMyApp.shouldOpenDialog) {
                rateMyApp.showRateDialog(context);
              }
            },
```

Can anyone tell me what's wrong?
Thanks

**Comment by Skyost** [comment]
Well, they told you the precise reason :

> We noticed that your app includes content and features that can manipulate user reviews for your app on the App Store. Specifically, your app filters user reviews and only directs users who intend to rate your app 4 - 5 stars to complete a rating on the App Store.

See [How it works](https://github.com/Skyost/RateMyApp#how-it-works) :

![Screenshot_1](https://user-images.githubusercontent.com/3882599/115110241-a5b71e00-9f7a-11eb-9333-d587765217b0.png)

**Comment by simo9900** [comment]
I used showratedialog which It not mention any conditional star rating to redirect or not user. 

It means that I should use always showstarratedialog instead?

**Comment by Skyost** [comment]
@simo9900 Imo, it really depends on who is reviewing your app. Still, my advise is to use their native app dialog.
