### ISSUE TITLE
Icon in dialog? 

### ISSUE THREAD

**Issue by thecreativedg** [Skyost/RateMyApp#99]
Is it possible to have icon of the app in dialog like this? thnx

![alert_with_icon_2.png](https://user-images.githubusercontent.com/6277278/119053528-799e1b00-b9c6-11eb-892c-85f15fd10315.png)

**Comment by Skyost** [comment]
Well erm nop. But if you _really_ want a custom icon, you can just show a custom dialog with 

```dart
actions: [
  RateMyAppRateButton(
    rateMyApp,
    text: 'Rate',
    validator: () => RateMyAppDialogButton.rate,
  ),
  RateMyAppLaterButton(
    rateMyApp,
    text: 'Later',
    validator: () => RateMyAppDialogButton.later,
  ),
  RateMyAppNoButton(
    rateMyApp,
    text: 'No',
    validator: () => RateMyAppDialogButton.no,
  ),
]
```

instead of calling `rateMyApp.showRateDialog()`. I think something like that will work.

**Comment by thecreativedg** [comment]
great, thank you!

**Comment by Skyost** [comment]
You're welcome :wink:
